-- Supprimer les contraintes uniques sur EQUIPMENT
DROP INDEX IF EXISTS UKJYCHFWYH3DHXN9E2JOMRLBCWR_INDEX_E;
DROP INDEX IF EXISTS UKAGM98WN5LN6UOH6O9HX25OGIC_INDEX_E;
DROP INDEX IF EXISTS PUBLIC.UKJYCHFWYH3DHXN9E2JOMRLBCWR_INDEX_E;
DROP INDEX IF EXISTS PUBLIC.UKAGM98WN5LN6UOH6O9HX25OGIC_INDEX_E;

-- Supprimer aussi les contraintes nommées différemment
ALTER TABLE IF EXISTS EQUIPMENT DROP CONSTRAINT IF EXISTS UKJYCHFWYH3DHXN9E2JOMRLBCWR;
ALTER TABLE IF EXISTS EQUIPMENT DROP CONSTRAINT IF EXISTS UKAGM98WN5LN6UOH6O9HX25OGIC;
